use ubuntu-22.04 instead of ubuntu-latest
this fixes the below workflow error

Package libgl1-mesa-glx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgl1-mesa-glx' has no installation candidate
Error: Process completed with exit code 100.