Do not Process if Git Does not exist
fix
Error:
Traceback (most recent call last):
  File "C:\Users\Nossea\DOWNLO~1\RIMSOR~1\RimSort\app\views\main_content_panel.py", line 2294, in _do_clone_repo_to_path
NameError: name 'Repo' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nossea\DOWNLO~1\RIMSOR~1\RimSort\app\views\main_content_panel.py", line 3186, in _on_do_download_steam_workshop_db_from_github
  File "C:\Users\Nossea\DOWNLO~1\RIMSOR~1\RimSort\app\views\main_content_panel.py", line 2300, in _do_clone_repo_to_path
NameError: name 'GitCommandError' is not defined